language: elixir
elixir:
  - 1.3.2
otp_release:
  - 18.2
install:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get
script:
  - mix test
notifications:
  recipients:
    - serneum@gmail.com
